### ISSUE TITLE
关于温度传感器的选用

### ISSUE THREAD

**Issue by kingmos** [xfce/PlayESP#1]
温度传感器用si7021吧，比10小还精确。

**Comment by kingmos** [comment]
另外希望增加Co2和攀腾的传感器接口。

**Comment by xfce** [comment]
@kingmos CO2和攀腾PM 已经加入V1.1 硬件需求。温湿度的我再看看si7021的规格书和价格

**Comment by xfce** [comment]
CO2和PM2.5传感器接口已增加，使用si7021
